# Generated by Django 4.2.7 on 2024-03-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movie_images'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
